import type { Metadata } from "next"
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs"
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar"
import { Toaster } from "sonner"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.variable} font-sans antialiased min-h-screen flex flex-col`}
        >
          {/* Top Auth Bar */}
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-10 px-5">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>

          {/* Navbar */}
          <Navbar />

          {/* Page Content */}
          <div className="md:bg-[#F4F2EE] flex-1 w-full">
            <main className="max-w-6xl mx-auto w-full">
              {children}
            </main>
          </div>

          {/* Toasts */}
          <Toaster position="top-right" />
        </body>
      </html>
    </ClerkProvider>
  )
}